package tirsobikes.views.orcamento;

import tirsobikes.views.venda.*;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import tirsobikes.DAO.EstoqueDAO;
import tirsobikes.DAO.ItensVendaDAO;
import tirsobikes.DAO.OrcamentoDAO;
import tirsobikes.DAO.VendaDAO;
import tirsobikes.controllers.*;
import tirsobikes.entidades.*;
import tirsobikes.funcoes.Converter;
import tirsobikes.funcoes.FormatarData;
import tirsobikes.funcoes.FormatarHora;
import tirsobikes.main.TirsoBikes;
import tirsobikes.views.validacoes.Validacoes;

/**
 *
 * @author Rafael
 */
public class OrcamentoView extends javax.swing.JFrame {


    char status = 1;

    public OrcamentoView() {
        initComponents();
        preecheDataHora();
//        orcamento.(status);
    }
    List<Itensvenda> itens = new ArrayList<Itensvenda>();
    Orcamento orcamento = new Orcamento();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtIdVenda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDataVenda = new javax.swing.JTextField();
        txtHoraVenda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtContatoCliente = new javax.swing.JTextField();
        jComboVendedor = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        bntBuscarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        bntAlterar = new javax.swing.JButton();
        bntAddProduto = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotalItens = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValorTotalItens = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescontoValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        bntAddServico = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboFormaPagamento = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDataPagamento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescontoPorcentagem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PEDIDO DE VENDAS");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEDIDO DE VENDA", 0, 0, new java.awt.Font("Calibri", 0, 11))); // NOI18N

        jLabel7.setText("Nº");

        txtIdVenda.setEditable(false);
        txtIdVenda.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtIdVenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIdVenda.setText("0");

        jLabel8.setText("Data");

        txtDataVenda.setEditable(false);
        txtDataVenda.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtDataVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataVenda.setText("00/00/0000");

        txtHoraVenda.setEditable(false);
        txtHoraVenda.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtHoraVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoraVenda.setText("00:00");

        jLabel9.setText("Hora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtIdVenda)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtHoraVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addComponent(txtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoraVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIÇÃO COMPRADOR", 0, 0, new java.awt.Font("Calibri", 0, 11))); // NOI18N

        jLabel10.setText("Nome");

        txtNomeCliente.setEditable(false);
        txtNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel11.setText("Contato / Outras informações");

        txtContatoCliente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jComboVendedor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin" }));

        jLabel12.setText("Atendente / Vendedor");

        bntBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tirsobikes/imgs/search.png"))); // NOI18N
        bntBuscarCliente.setText(" Pesquisar Cliente");
        bntBuscarCliente.setMargin(new java.awt.Insets(2, 2, 2, 14));
        bntBuscarCliente.setPreferredSize(new java.awt.Dimension(133, 27));
        bntBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtContatoCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jComboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(1, 1, 1)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bntBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, 0)
                        .addComponent(txtContatoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jComboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaVendas.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Tipo", "Cód.", "Descrição", "Quant.", "Valor Unit.", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaVendas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaVendas);
        if (tabelaVendas.getColumnModel().getColumnCount() > 0) {
            tabelaVendas.getColumnModel().getColumn(0).setPreferredWidth(20);
            tabelaVendas.getColumnModel().getColumn(1).setPreferredWidth(20);
            tabelaVendas.getColumnModel().getColumn(2).setPreferredWidth(30);
            tabelaVendas.getColumnModel().getColumn(3).setPreferredWidth(350);
            tabelaVendas.getColumnModel().getColumn(4).setPreferredWidth(50);
            tabelaVendas.getColumnModel().getColumn(5).setPreferredWidth(90);
            tabelaVendas.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        bntAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tirsobikes/imgs/alterar.png"))); // NOI18N
        bntAlterar.setText(" Alterar");
        bntAlterar.setMargin(new java.awt.Insets(2, 2, 2, 14));
        bntAlterar.setPreferredSize(new java.awt.Dimension(133, 27));
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });

        bntAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tirsobikes/imgs/produto.png"))); // NOI18N
        bntAddProduto.setText("     Adicionar Produto");
        bntAddProduto.setMargin(new java.awt.Insets(2, 2, 2, 14));
        bntAddProduto.setPreferredSize(new java.awt.Dimension(133, 27));
        bntAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddProdutoActionPerformed(evt);
            }
        });

        bntExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tirsobikes/imgs/delete (1).png"))); // NOI18N
        bntExcluir.setText(" Excluir");
        bntExcluir.setMargin(new java.awt.Insets(2, 2, 2, 14));
        bntExcluir.setPreferredSize(new java.awt.Dimension(133, 27));
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("TOTAL ITENS");

        txtTotalItens.setEditable(false);
        txtTotalItens.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTotalItens.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("VALOR TOTAL ITENS R$");

        txtValorTotalItens.setEditable(false);
        txtValorTotalItens.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtValorTotalItens.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("( - ) DESCONTO R$");

        txtDescontoValor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDescontoValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDescontoValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescontoValorKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("TOTAL R$");

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 204));
        txtTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N

        bntSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tirsobikes/imgs/save.png"))); // NOI18N
        bntSalvar.setText("SALVAR ORÇAMENTO");
        bntSalvar.setMargin(new java.awt.Insets(2, 2, 2, 14));
        bntSalvar.setPreferredSize(new java.awt.Dimension(133, 27));
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tirsobikes/imgs/cancel.png"))); // NOI18N
        bntCancelar.setText(" CANCELAR ORÇAMENTO");
        bntCancelar.setMargin(new java.awt.Insets(2, 2, 2, 14));
        bntCancelar.setPreferredSize(new java.awt.Dimension(133, 27));
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        bntAddServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tirsobikes/imgs/servico.png"))); // NOI18N
        bntAddServico.setText("     Adicionar Serviço");
        bntAddServico.setMargin(new java.awt.Insets(2, 2, 2, 14));
        bntAddServico.setPreferredSize(new java.awt.Dimension(133, 27));
        bntAddServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddServicoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAGAMENTO", 0, 0, new java.awt.Font("Calibri", 0, 11))); // NOI18N

        jComboFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A VISTA", "CHEQUE", "A PRAZO" }));
        jComboFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboFormaPagamentoActionPerformed(evt);
            }
        });

        jLabel13.setText("Forma Pagto.");

        jLabel14.setText("Data Pagto.");

        txtDataPagamento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jComboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.setPlaceholderCharacter(' ');
            txtDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascara));
        }   catch (java.text.ParseException ex) {  ex.printStackTrace();  }

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("( - ) DESCONTO %");

        txtDescontoPorcentagem.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDescontoPorcentagem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDescontoPorcentagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescontoPorcentagemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bntAddServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bntAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDescontoValor, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(txtDescontoPorcentagem)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalItens, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtValorTotalItens))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntAddServico, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalItens, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorTotalItens, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescontoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescontoPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        if (!validaCampos()) {
            return;
        }

        this.orcamento.setDataHora(FormatarData.juntaDataHota(txtDataVenda.getText(), txtHoraVenda.getText()));
        this.orcamento.setDataPagamento(FormatarData.forDB(txtDataPagamento.getText()));
        if (!txtDescontoValor.getText().isEmpty()) {
            this.orcamento.setDesconto(Double.parseDouble(txtDescontoValor.getText().replace(".", "").replace(",", ".")));
        }
        this.orcamento.setFormaPagamento(jComboFormaPagamento.getSelectedItem().toString());
        this.orcamento.setValorFinal(Double.parseDouble(txtTotal.getText().replace(".", "").replace(",", ".")));
        this.orcamento.setInformacoes(txtContatoCliente.getText());

        OrcamentoDAO dao = new OrcamentoDAO(TirsoBikes.getEntityManager());

        this.orcamento = dao.salvarOrcamento(orcamento);



        ItensVendaDAO daoItem = new ItensVendaDAO(TirsoBikes.getEntityManager());

        for (Itensvenda item : this.itens) {
            item.setIditensVenda(null);
            item.setIdvenda(orcamento);
            daoItem.salvaritensVenda(item);
            if (item.getTipo().equals("P")) {
                baixaEstoque(item.getIdproduto(), item.getQuantidade());
            }
        }
        limpaCampos();

    }//GEN-LAST:event_bntSalvarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed

        int linhaTabela = tabelaVendas.getSelectedRow();
        if (linhaTabela > -1) {
            int codigo = Integer.parseInt(tabelaVendas.getValueAt(linhaTabela, 0).toString());
            Itensvenda itemAux = new Itensvenda();
            for (Itensvenda item : this.itens) {
                if (item.getIditensVenda() == codigo) {
                    itemAux = item;
                }
            }

            itens.remove(itemAux);
            atualizaTabela();
        }
    }//GEN-LAST:event_bntExcluirActionPerformed
    private void bntAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddProdutoActionPerformed
        ProdutoListaController.getInstancia().exibirInterfaceGrafica(this);
    }//GEN-LAST:event_bntAddProdutoActionPerformed

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        int linhaTabela = tabelaVendas.getSelectedRow();

        if (linhaTabela > -1) {
            int codigo = Integer.parseInt(tabelaVendas.getValueAt(linhaTabela, 0).toString());
            Itensvenda itemAux = new Itensvenda();
            for (Itensvenda item : this.itens) {
                if (item.getIditensVenda() == codigo) {
                    itemAux = item;
                }
            }
//            VendaAlterarProdutoController.getInstancia().exibirInterfaceGrafica(itemAux, this);
        }
    }//GEN-LAST:event_bntAlterarActionPerformed

    private void bntBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarClienteActionPerformed
        ClienteListarController.getInstancia().exibirInterfaceGrafica(this);
    }//GEN-LAST:event_bntBuscarClienteActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        Integer resposta = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja sair? \n Todos os dados serão perdidos.");
        if (resposta == JOptionPane.YES_OPTION) {
            limpaCampos();
            this.dispose();
        }
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void bntAddServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddServicoActionPerformed
        ServicoListaController.getInstancia().exibirInterfaceGrafica(this);
    }//GEN-LAST:event_bntAddServicoActionPerformed

    private void txtDescontoValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoValorKeyReleased
        if (txtDescontoValor.getText().isEmpty()) {
            txtDescontoValor.setText("0");
        }

        if (!txtDescontoValor.getText().isEmpty() && Validacoes.validaNumero(txtDescontoValor.getText()) && !txtValorTotalItens.getText().isEmpty()) {
            Venda venda = new Venda();
            venda.setDesconto(Double.parseDouble(Converter.banco(txtDescontoValor.getText())));
            venda.setValorTotal(Double.parseDouble(Converter.banco(txtValorTotalItens.getText())));

            // seta percentual de desconto
            Double percentual = (venda.getDesconto() * 100) / venda.getValorTotal();
            txtDescontoPorcentagem.setText(percentual.toString());

            // seta valor atualizado com desconto
            venda.setValorTotal(venda.getValorTotal() - venda.getDesconto());
            txtTotal.setText(String.valueOf(venda.getValorTotalView().replace("R$ ", "")));
        } else {
            atualizaTabela();
        }
    }//GEN-LAST:event_txtDescontoValorKeyReleased

    private void txtDescontoPorcentagemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoPorcentagemKeyReleased
        if (txtDescontoPorcentagem.getText().isEmpty()) {
            txtDescontoPorcentagem.setText("0");
        }

        if (!txtDescontoPorcentagem.getText().isEmpty() && Validacoes.validaNumero(txtDescontoPorcentagem.getText()) && !txtValorTotalItens.getText().isEmpty()) {
            Venda venda = new Venda();
            Double percentual = Double.parseDouble(Converter.banco(txtDescontoPorcentagem.getText()));
            venda.setValorTotal(Double.parseDouble(Converter.banco(txtValorTotalItens.getText())));

            // seta percentual de desconto
            venda.setDesconto((percentual * venda.getValorTotal()) / 100);
            txtDescontoValor.setText(venda.getDescontoView().replace("R$ ", ""));

            // seta valor atualizado com desconto
            venda.setValorTotal(venda.getValorTotal() - venda.getDesconto());
            txtTotal.setText(String.valueOf(venda.getValorTotalView().replace("R$ ", "")));
        } else {
            atualizaTabela();
        }
    }//GEN-LAST:event_txtDescontoPorcentagemKeyReleased

    private void jComboFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboFormaPagamentoActionPerformed

        if (jComboFormaPagamento.getSelectedIndex() == 0) {
            this.status = 1;
            this.orcamento.setStatusPagamento(status);
        } else {
            this.status = 0;
            this.orcamento.setStatusPagamento(status);
        }

    }//GEN-LAST:event_jComboFormaPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrcamentoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrcamentoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrcamentoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrcamentoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrcamentoView().setVisible(true);
            }
        });
    }

    private void preecheDataHora() {
        Date data = new Date();
        String dataFormatada = FormatarData.forUser(data);
        txtDataVenda.setText(dataFormatada);
        String horaFormatada = FormatarHora.forUser(data);
        txtHoraVenda.setText(horaFormatada);
        txtDataPagamento.setText(dataFormatada);
    }
    int contadorItens = 0;

    public void addProdutoServico(Itensvenda item) {
        //verifica se ja existe o item na lista
        if (item.getIditensVenda() == null) {
            contadorItens += 1;
            item.setIditensVenda(contadorItens);
        } else {
            //remove registro anterior, antes de adicionar o atualizado
            this.itens.remove(item);
        }
        this.itens.add(item);
        atualizaTabela();
    }
    NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

    private void atualizaTabela() {
        DefaultTableModel dtm = (DefaultTableModel) tabelaVendas.getModel();
        dtm.setRowCount(0);
        Double total = 0.0;
        Integer totalItens = 0;
        if (!this.itens.isEmpty()) {
            for (Itensvenda i : this.itens) {
                if (i.getIdproduto() != null) {
                    dtm.addRow(new Object[]{i.getIditensVenda(), i.getTipo(), i.getIdproduto().getIdproduto(), i.getIdproduto().getDescricao(), i.getQuantidade(), i.getPrecoUnitarioView(), i.getTotalView()});
                } else {
                    dtm.addRow(new Object[]{i.getIditensVenda(), i.getTipo(), i.getIdservico().getIdservico(), i.getIdservico().getDescricao(), i.getQuantidade(), i.getPrecoUnitarioView(), i.getTotalView()});
                }
                total += i.getTotal();

                if (i.getTipo().equals("P")) {
                    totalItens += i.getQuantidade();
                }
            }
        }

        txtTotalItens.setText(totalItens.toString());

        Double totalValorItens = total;

        if (!txtDescontoValor.getText().isEmpty() && Validacoes.validaNumero(txtDescontoValor.getText())) {
            total -= Double.parseDouble(Converter.banco(txtDescontoValor.getText()));
        }

        String totalItensFormatado = nf.format(totalValorItens);
        txtValorTotalItens.setText(totalItensFormatado.replace("R$ ", ""));

        String totalFormatado = nf.format(total);
        txtTotal.setText(totalFormatado.replace("R$ ", ""));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAddProduto;
    private javax.swing.JButton bntAddServico;
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntBuscarCliente;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JComboBox jComboFormaPagamento;
    private javax.swing.JComboBox jComboVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVendas;
    private javax.swing.JTextField txtContatoCliente;
    private javax.swing.JFormattedTextField txtDataPagamento;
    private javax.swing.JTextField txtDataVenda;
    private javax.swing.JTextField txtDescontoPorcentagem;
    private javax.swing.JTextField txtDescontoValor;
    private javax.swing.JTextField txtHoraVenda;
    private javax.swing.JTextField txtIdVenda;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalItens;
    private javax.swing.JTextField txtValorTotalItens;
    // End of variables declaration//GEN-END:variables

    public void addCliente(Cliente cliente) {
        txtNomeCliente.setText(cliente.getNomeCompleto());
        this.orcamento.setIdcliente(cliente);
    }

    private boolean validaCampos() {
        if (txtNomeCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Cliente");
            bntBuscarCliente.doClick();
            return false;
        }

        if (this.itens.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Venda sem itens");
            return false;
        }

        return true;
    }

    private void limpaCampos() {
        txtContatoCliente.setText("");
        txtNomeCliente.setText("");
        txtDescontoPorcentagem.setText("");
        txtDescontoValor.setText("");
        txtValorTotalItens.setText("");
        txtTotal.setText("");
        txtTotalItens.setText("");
        jComboFormaPagamento.setSelectedIndex(0);

        preecheDataHora();

        DefaultTableModel dtm = (DefaultTableModel) tabelaVendas.getModel();
        dtm.setRowCount(0);

        this.itens = null;
        this.orcamento = null;
    }

    private void baixaEstoque(Produto produto, int quantidade) {
        EstoqueDAO dao = new EstoqueDAO(TirsoBikes.getEntityManager());
        List<Estoque> estoques = dao.ultimoEstoque(produto.getIdproduto());
        Estoque estoque = estoques.get(0);
        estoque.setQuantidade(estoque.getQuantidade() - quantidade);
        estoque.setData(this.orcamento.getDataHora());
        estoque.setIdvenda(orcamento);
        dao.salvarEstoque(estoque);
    }
}
